path: /home/trungminh/HK2/CNPM/bug-scanner/ml-training/datasets/ip102-yolo
train: images/train
val: images/val
test: images/test
names:
  0: 'Cnaphalocrocis medinalis'
  1: 'Naranga aenescens'
  2: 'Hydrellia philippina'
  3: 'Chilo suppressalis'
  4: 'Scirpophaga incertulas'
  5: 'Orseolia oryzae'
  6: 'Atherigona exigua'
  7: 'Nilaparvata lugens'
  8: 'Sogatella furcifera'
  9: 'Laodelphax striatellus'
  10: 'Lissorhoptrus oryzophilus'
  11: 'Nephotettix cincticeps'
  12: 'Stenchaetothrips biformis'
  13: 'Scotinophara lurida'
  14: 'Holotrichia sp.'
  15: 'Gryllotalpidae'
  16: 'Elateridae'
  17: 'Spilosoma lubricipeda'
  18: 'Agrotis ipsilon'
  19: 'Agrotis tokionis'
  20: 'Agrotis segetum'
  21: 'Tetranychus urticae'
  22: 'Ostrinia furnacalis'
  23: 'Mythimna separata'
  24: 'Aphididae'
  25: 'Potosia brevitarsis'
  26: 'Carposina sasakii'
  27: 'Sitobion avenae'
  28: 'Schizaphis graminum'
  29: 'Rhopalosiphum padi'
  30: 'Sitodiplosis mosellana'
  31: 'Penthaleus major'
  32: 'Linopodes sp.'
  33: 'Haplothrips tritici'
  34: 'Cephus cinctus'
  35: 'Cerodontha denticornis'
  36: 'Pegomya hyoscyami'
  37: 'Phyllotreta striolata'
  38: 'Mamestra brassicae'
  39: 'Spodoptera exigua'
  40: 'Scrobipalpa ocellatella'
  41: 'Loxostege sticticalis'
  42: 'Bothynoderes punctiventris'
  43: 'Serica orientalis'
  44: 'Hypera postica'
  45: 'Heliothis viriplaca'
  46: 'Adelphocoris lineolatus'
  47: 'Lygus lineolaris'
  48: 'Locustoidea'
  49: 'Lytta polita'
  50: 'Epicauta gorhami'
  51: 'Meloidae'
  52: 'Therioaphis maculata'
  53: 'Odontothrips loti'
  54: 'Thripidae'
  55: 'Bruchophagus roddi'
  56: 'Pieris canidia'
  57: 'Apolygus lucorum'
  58: 'Limacodidae'
  59: 'Daktulosphaira vitifoliae'
  60: 'Colomerus vitis'
  61: 'Brevipalpus lewisi'
  62: 'Oides decempunctata'
  63: 'Polyphagotarsonemus latus'
  64: 'Pseudococcus comstocki'
  65: 'Paranthrene regalis'
  66: 'Ampelophaga rubiginosa'
  67: 'Lycorma delicatula'
  68: 'Xylotrechus quadripes'
  69: 'Cicadella viridis'
  70: 'Miridae'
  71: 'Trialeurodes vaporariorum'
  72: 'Erythroneura apicalis'
  73: 'Papilio xuthus'
  74: 'Panonychus citri'
  75: 'Phyllocoptruta oleivora'
  76: 'Icerya purchasi'
  77: 'Unaspis yanonensis'
  78: 'Ceroplastes rubens'
  79: 'Chrysomphalus aonidum'
  80: 'Parlatoria zizyphi'
  81: 'Nipaecoccus viridis'
  82: 'Aleurocanthus spiniferus'
  83: 'Bactrocera minax'
  84: 'Bactrocera dorsalis'
  85: 'Bactrocera tsuneonis'
  86: 'Spodoptera litura'
  87: 'Adris tyrannus'
  88: 'Phyllocnistis citrella'
  89: 'Toxoptera citricida'
  90: 'Toxoptera aurantii'
  91: 'Aphis spiraecola'
  92: 'Scirtothrips dorsalis'
  93: 'Dasineura sp.'
  94: 'Lawana imitata'
  95: 'Salurnis marginellus'
  96: 'Deporaus marginatus'
  97: 'Chlumetia transversa'
  98: 'Idioscopus clypealis'
  99: 'Rhytidodera bowringii'
  100: 'Sternochetus frigidus'
  101: 'Cicadellidae'
