path: /home/trungminh/HK2/CNPM/bug-scanner/ml-training/datasets/vietnam-practical-yolo
train: images/train
val: images/val
test: images/test
names:
  0: 'rice leaf folder'
  1: 'rice leaf caterpillar'
  2: 'rice stem borer'
  3: 'rice stem maggot'
  4: 'rice gall midge'
  5: 'brown planthopper'
  6: 'white backed planthopper'
  7: 'small brown planthopper'
  8: 'green leafhopper'
  9: 'rice thrips'
  10: 'rice bug'
  11: 'soil grub'
  12: 'mole cricket'
  13: 'wireworm'
  14: 'cutworm'
  15: 'spider mite'
  16: 'corn borer'
  17: 'armyworm'
  18: 'aphid'
  19: 'flea beetle'
  20: 'cabbage caterpillar'
  21: 'locust or grasshopper'
  22: 'thrips'
  23: 'hairy caterpillar'
  24: 'scale insect or mealybug'
  25: 'longhorn borer'
  26: 'mirid bug'
  27: 'whitefly'
  28: 'fruit fly'
  29: 'citrus leafminer'
  30: 'mango hopper'
  31: 'mango borer or weevil'
  32: 'leafhopper'
