name: Auto Update iNaturalist Token

on:
  # Chạy tự động vào lúc 00:00 và 12:00 mỗi ngày
  schedule:
    - cron: "0 0,12 * * *" 
  # Cho phép bạn bấm nút chạy bằng tay trên web để test
  workflow_dispatch: 

jobs:
  update-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests firebase-admin

      - name: Run Python Script to Fetch Token & Update Firestore
        env:
          INAT_USERNAME: ${{ secrets.INAT_USERNAME }}
          INAT_PASSWORD: ${{ secrets.INAT_PASSWORD }}
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        run: python .github/scripts/update_inat_token.py